fix: issue #112
topcoder-platform/taas-app pull request #262
Opened 2021-05-15 14:01 UTC by yoution

2021-05-15 14:01 UTC, yoution commented
@maxceem please review

2021-05-17 08:54 UTC, maxceem requested changes
@yoution strange, but for me it doesn't work. Does it work for you?

![image](https://user-images.githubusercontent.com/146016/118461761-acb28700-b706-11eb-8084-f47e8eaf005c.png)

2021-05-17 08:54 UTC, maxceem commented on src/hoc/withAuthentication/index.js
> +          <LoadingIndicator error={"Error: Network Error"} />
@yoution sorry, I didn't mean to show error `Network Error` I mean to show error which happens during loading user profile. We have to pass it there.

2021-05-17 08:54 UTC, maxceem commented on src/hoc/withAuthentication/actions/index.js
> +export const authLoadUserProfile = (teamId) => ({
argument `teamId` is not used

2021-05-17 08:56 UTC, maxceem commented
@yoution also, could we please name action as `AUTH_LOAD_V5_USER_PROFILE` instead of `AUTH_LOAD_USER_PROFILE` to keep it clear. Because we also have another user profile (v3).

2021-05-17 09:12 UTC, yoution commented on src/hoc/withAuthentication/index.js
> +          <LoadingIndicator error={"Error: Network Error"} />
I don't know how to repreduce the error case

2021-05-17 09:15 UTC, yoution commented on src/hoc/withAuthentication/index.js
> +          <LoadingIndicator error={"Error: Network Error"} />
![image](https://user-images.githubusercontent.com/3863914/118464422-69bad880-b733-11eb-9f66-b59e1dff0f70.png)
it works for me

2021-05-17 09:16 UTC, maxceem commented on src/hoc/withAuthentication/index.js
> +          <LoadingIndicator error={"Error: Network Error"} />
you may change endpoint to incorrect one, like below, it should cause some error during request, and it should be shown on the page
```js
return axios.get(`${config.API.V5}/taas-teams/meBROKEN`);
```

2021-05-17 09:46 UTC, yoution commented on src/hoc/withAuthentication/index.js
> +          <LoadingIndicator error={"Error: Network Error"} />
![image](https://user-images.githubusercontent.com/3863914/118468846-be605280-b737-11eb-8008-830840a002c6.png)
how about this

2021-05-17 10:10 UTC, maxceem commented on src/hoc/withAuthentication/index.js
> +          <LoadingIndicator error={"Error: Network Error"} />
yeah, looks good, this is what was needed

2021-05-18 07:31 UTC, maxceem requested changes
@yoution it works almost perfect for me locally.

But there is a small improvement to make.
When we wait for v5 user profile loading, the loading indicator has to be shown

![image](https://user-images.githubusercontent.com/146016/118609231-3758bc00-b7c3-11eb-90fa-cae8f384a6db.png)

It's hard to see, but when V5 user profile is being loaded, the loading indicator is not shown, see how it looks if I slow down loading of v5 user profile to 10 seconds https://monosnap.com/file/CuX6Ahly89FgAdpn1QJFRgh7OcJRF9

How to reproduce it. In file `src/services/teams.js`
- add import `import { delay } from "utils/helpers";` on line 6
- update code of `getUserProfile` to
  ```js
    export const getUserProfile = () => {
      return delay(10000).then(() => axios.get(`${config.API.V5}/taas-teams/me`));
    };  
  ```
  
So you could see how it would look like if loading of V5 user profile is slow.

It would be nice (but not required) if existent code could be reused, we already have 2 places in code: 1 place to show loading indicator or error, and another one to show component if all is loaded:

![image](https://user-images.githubusercontent.com/146016/118609918-ec8b7400-b7c3-11eb-9f53-2e987bc5f6a1.png)

One more thing.
Could we please also rename 
- action method `authLoadUserProfile` to `authLoadV5UserProfile`
- and service method `getUserProfile` to `getV5UserProfile`

to make it clear that this is for V5 user profile to avoid confusion in the future.

2021-05-18 18:21 UTC, maxceem approved these changes
@yoution thanks for the quick updates. Works good now.

2021-05-18 18:22 UTC, merged