Feature/fix issue
topcoder-platform/taas-app pull request #40
Opened 2021-01-03 11:23 UTC by yoution

@maxceem three issues  are merged in this one commit

2021-01-05 20:52 UTC, maxceem requested changes
@yoution all works good.

There are a few code improvements, see comments below.

2021-01-05 20:53 UTC, maxceem commented on package.json
> +    "build:prod": "webpack --mode=${APPMODE:-production} --env.config=${APPENV:-prod}",
@yoution we don't need to add the second `build:prod` as we can just set env variable `APPMODE=production` and run `npm run build`, see https://github.com/topcoder-platform/taas-app/issues/13#issuecomment-754891697

2021-01-06 12:29 UTC, yoution commented
@maxceem please review

2021-01-06 21:56 UTC, maxceem approved these changes
Thanks for the quick update @yoution. Perfect now.

2021-01-06 21:56 UTC, merged