fix: error message for #44
topcoder-platform/taas-app pull request #47
Opened 2021-01-08 05:57 UTC by yoution

@maxceem please review for #44

2021-01-09 13:39 UTC, maxceem requested changes
There is one missing requirement and a couple of small improvements for the code.

    > If the promise is rejected, then some error happens during Authentication. So instead of the page, we have to show an error message.
    
   Imagine if some error happens during authentication. To simulate it we can add `throw new Error("Auth error");` inside `getAuthUserTokens` method:
    
    ![image](https://user-images.githubusercontent.com/146016/104092918-d60e6280-528f-11eb-9ac2-4b2c014252a0.png)
    
    As a result error would happen during loading. This error should be shown, but the moment empty page is show:

    ![image](https://user-images.githubusercontent.com/146016/104092908-c42cbf80-528f-11eb-8d1a-ebec82adb4ca.png)

2021-01-09 13:39 UTC, maxceem commented on src/components/Authentication/index.jsx
> +      </div>
@yoution it would be better not to add `<div>` so we don't add any additional markup, and just render pages directly.

2021-01-09 13:39 UTC, maxceem commented on src/components/Authentication/index.jsx
> +export default function Authentication(Component) {
@yoution as this is a HOC let's use the usual naming such components and name it `withAuthentication` here, and when we use it.

2021-01-09 14:25 UTC, yoution commented
@maxceem please review

2021-01-10 09:04 UTC, maxceem approved these changes
@yoution all good now, thanks.

2021-01-10 09:04 UTC, merged