Added interview cancel & reschedule page.
topcoder-platform/taas-app pull request #574
Opened 2021-11-08 08:10 UTC by mahidulalvi-bonic

2021-11-08 08:28 UTC, maxceem requested changes
@mahidulalvi-bonic looks like these pages are broken for me client-side

https://monosnap.com/file/bIeoFgudOR9Nfr6WMXxKPABKJBOhdj

Does it work for you?

2021-11-08 10:30 UTC, mahidulalvi-bonic commented
@maxceem, sorry, some last minute changes had imports missing. Fixed now.

2021-11-08 10:35 UTC, maxceem commented on src/routes/RescheduleInterviewPage/index.jsx
> +  // if there are some candidates to review, then show "To Review" tab by default
Looks like a redundant comment

2021-11-08 10:35 UTC, maxceem commented on src/routes/RescheduleInterviewPage/index.jsx
> +          setErrorMessage(`This interview has status ${data.status} and cannot be cancelled.`);
Typo in message, should be `rescheduled` instead of `cancelled`: `This interview has status ${data.status} and cannot be rescheduled.`

2021-11-08 10:38 UTC, maxceem requested changes
@mahidulalvi-bonic it seems to looks good, just a few minor things in comments above.

Though I could only fully verify it, after API side works good, as now links a are broken without `edit hash`.

2021-11-08 10:55 UTC, mahidulalvi-bonic commented on src/routes/RescheduleInterviewPage/index.jsx
> +  // if there are some candidates to review, then show "To Review" tab by default
Done in latest commit.

2021-11-08 10:56 UTC, mahidulalvi-bonic commented on src/routes/RescheduleInterviewPage/index.jsx
> +          setErrorMessage(`This interview has status ${data.status} and cannot be cancelled.`);
Done in latest commit.

2021-11-08 11:14 UTC, mahidulalvi-bonic commented
@maxceem, I checked the links and it works and event hash also getting saved in DB after the fixes. Can you please test now?

My test was broken midway as rescheduling the interview triggered a cancel event, but may be we need to add code for handling update events(currently we have create and update)? But it would be great to know how it works for you.

2021-11-08 11:17 UTC, mahidulalvi-bonic commented
Actually, my test worked. The reschedule was done correctly. That error was because, before rescheduling, the event is cancelled(? - reading the logs). But after some moments, I saw the rescheduled notification in terminal.

2021-11-08 11:22 UTC, maxceem commented
> My test was broken midway as rescheduling the interview triggered a cancel event, but may be we need to add code for handling update events(currently we have create and update)?
> That error was because, before rescheduling, the event is cancelled(? - reading the logs)

So did rescheduling worked for you or no?

Rescheduling in Nylas works like this:
1. first they create a new event (webhook triggered)
2. after that they cancel previous event (that's why we check in update webhook `interview.nylasEventId === event.id` to make sure that cancelled event is the current event). As on step we already updated `nylasEventId` so this interview should not get cancelled.

Does this workflow works good for you?

2021-11-08 11:52 UTC, mahidulalvi-bonic commented
> > My test was broken midway...
> Does this workflow works good for you?

It worked, although I misread the logs when I saw
`Get event details error, 404`
I think this was because the event was already deleted.

So workflow works good for me I think..

2021-11-08 11:59 UTC, maxceem commented
@mahidulalvi-bonic I'm currently testing it out but the weird thing is that new webhook (like `https://2e58-77-120-181-211.ngrok.io/api/v5/updateInterview/b0f22cc1-fa35-4fb3-8d1d-8f9462d76201/nylas-webhooks`) is never called for me.

Could you please, try scheduling and accepting a new meeting one more time and check if a new webhook works for you now. (it worked for me previously, but now seems something broken and I cannot understand if I'm doing something wrong, of something has broken on the Nylas side)

2021-11-08 12:37 UTC, mahidulalvi-bonic commented
@maxceem, I tried again and it works for me. Did you create a webhook in the Nylas dashboard for the global endpoint? And also, does this url match with what is set in file `NylasService` (https://github.com/topcoder-platform/taas-apis/blob/a336c1d2e3581fb5430378252adc02b007416036/src/services/NylasService.js#L136)?

And in the Nylas webhooks dashboard, the hook needs to be in running state, sometimes it goes into pause because it can't connect to API when API is down..

2021-11-08 12:41 UTC, maxceem commented
Thanks a lot checking it. I did check all these URL, but somehow it doesn't work for me. As it work for it must be something with my config, so I'm re-checking my config.

2021-11-09 05:15 UTC, mahidulalvi-bonic commented
@maxceem, I may have found the issue you had with webhook endpoint not being called. The env variable `TAAS_APP_BASE_URL` was not added to Git properly so it might have thrown silent errors in your case. For me, it was still in my file so I had the changes.

I pushed a fix for it in the latest commit.

2021-11-17 12:04 UTC, maxceem approved these changes
@mahidulalvi-bonic works good.

2021-11-17 12:04 UTC, merged