Added capability to inject custom validator
topcoder-platform/taas-app pull request #96
Opened 2021-02-13 18:04 UTC by dashu-baba

2021-02-16 17:13 UTC, maxceem requested changes
@dashu-baba idea with custom validator looks great, but the solution has a few issues for me:

1. Border should be below error message when there is more than 1 line:

    ![image](https://user-images.githubusercontent.com/146016/108094988-0d8ade80-7088-11eb-9a12-e45e2ac1a7ae.png)
    
2. If I enter 2 dates and see error, and then remove one date, the error is still there. But if we have only one date entered there should not be error shown:

    ![image](https://user-images.githubusercontent.com/146016/108095129-357a4200-7088-11eb-85c4-edaf3598097e.png)

Also, please, check the comments for the code below.

2021-02-16 17:13 UTC, maxceem commented on src/components/TextInput/index.jsx
> +      styleName={`TextInput ${props.className} ${props.readonly ? "readonly" : ""}`}
It would be nice to use `classnames` lib there to apply classes on conditions, like here https://github.com/topcoder-platform/taas-app/blob/dev/src/components/ActionsMenu/index.jsx#L78

2021-02-17 08:45 UTC, dashu-baba commented
@maxceem , Please check the latest fix. Thanks

2021-02-17 12:03 UTC, maxceem requested changes
@dashu-baba it works good now. 

But I still have concerns regarding the implementation.

I believe that such a code as `startDateField.showError = false;` still mutates the `props` implicitly, as `startDateField` is one of the `fields` and `fields` comes from props initially.

Also, such code as `meta.error && (meta.touched || field.showError)` looks hacky. The Final Form library already provides a way to check if the field has an error or no by `meta.error`. But in the implementation, you've added the second custom flag `field.showError` which should not be neccessary.

I believe there should be a way to implement the validation in such a way, that we can reuse `meta.error`.

I'd increase the payment for this ticket to `$50`, but we would like to have a solution that utilizes Final Form features properly without workadournds.

2021-02-17 16:55 UTC, dashu-baba commented
The final fix is:

> So if I edit endDate and put wrong value, we can show error message only for endDate it's ok if startDate doesn't have error messages at this moment
> if after that we touch startDate then error message would be shown there.

CC: @maxceem

2021-02-18 08:02 UTC, maxceem approved these changes
All good now @dashu-baba.

2021-02-18 08:02 UTC, merged